Goverla v2 transactions
sofigern/goverla pull request #2
Opened 2023-02-25 12:36 UTC by ludina001

Трохи пописав по трансакціям, створив базовий шаблон html від якої всі інші будуть наслідувати стилі та хедер, головну сторінку, а також предумав новий функціонал що буде перевіряти документи на прозорро та шукати повні збіги між доками у пропозиціях учасниках щоб виявляти можливі змови. Для цього функціоналу є всі вьюшки, шляхи, сторінка що рендерить форму та відмальовує результати.

2023-02-26 15:11 UTC, sofigern commented on api/templates/base.html
> +<html lang="uk">
:ukr:

2023-02-26 15:17 UTC, sofigern commented on api/templates/base.html
> +  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
Django підставляє нам bootstrap 5.1.3.
Думаю, що ця розбіжність версій може бути проблемою пізніше. Має сенс всюди використовувати одну й ту ж версію за можливості. Ми можем тут перевикористати Jinja виклик імпорту стилів.

{% load bootstrap5 %}

2023-02-26 15:20 UTC, sofigern commented
В мене доречі відображається json:

<img width="1094" alt="Screenshot 2023-02-26 at 17 19 24" src="https://user-images.githubusercontent.com/7364863/221419687-46ba3a55-df0d-4406-9d8a-2b2ac9afd5ff.png">

2023-02-26 15:22 UTC, sofigern commented on api/templates/base.html
> +  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
ЦікавоЮ що ми ці підключення робимо в <body> я думав, що вони переважно робляться в <head> зазвичай.

2023-02-26 15:28 UTC, ludina001 commented on api/templates/base.html
> +  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
відмальовує бо воно не наслідує з base.hml , я потестив та прибрав коли зрозуміі що воно зжирає функціонал з відмальовкою

2023-02-26 15:31 UTC, sofigern commented on src/api/v2/check_documents/lotForm.py
> +    lot_id = forms.CharField(label='ID лоту',
Звертай увагу на форматування. Можливо встанови flake8 плагін який буде радити щодо форматування коду згідно стандартів. Наступний код набагато легше читати

```
class LotForm(forms.Form):
    lot_id = forms.CharField(
        label='ID лоту',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control', 
                'placeholder': 'Введіть ID лоту',
            }
        )
    )
```

2023-02-26 15:34 UTC, sofigern commented on src/api/v2/check_documents/lotForm.py
> +                             widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введіть ID лоту'}))
Також пропоную замість TextInput, використати Textarea, це візульно допоможе користувачеві зрозуміти, що можна ввести більше ніж один лот.

Також можна розширити placeholder якимось прикладом, щоб легше було зрозуміти формат вводу, а також як мають бути розділені різні лоти, наприклад символами нового рядку, комами, абощо.

2023-02-26 15:37 UTC, sofigern commented on api/templates/goverla.html
> +    <p class="lead">Вітаю на Говерлі, порталі доступу до відкритих даних. На даний момент доступним є пошук по платежах та договорах з порталу відкритих фінансів. Якщо бажаєте допомогти розвитку проє
🙏

2023-02-26 15:39 UTC, sofigern commented on api/templates/goverla.html
> +        <a class="btn btn-primary btn-lg btn-block" href="#">Перейти до сервісу вивантаження платежів</a>
виглядає так що тут лінка не вірно підібрана `href="#"` але здається ми ще не створили коректної вьюшки на цей сервіс.

2023-02-26 15:47 UTC, sofigern commented on src/api/v2/check_documents/prozoro_document_check.py
> +    for i, first_bid in enumerate(bids):
В python є вже готовий вбудований фунціонал для таких задач:
```
from itertools import combinations

for first_bid, second_bid in combinations(bids, 2):
    .....
```

Наприклад:
```
print([(l, r) for l, r in combinations([1, 2, 3], 2)])
>  [(1, 2), (1, 3), (2, 3)]
```
Більше деталей тут: https://docs.python.org/3/library/itertools.html#itertools.combinations

2023-02-26 16:04 UTC, sofigern commented on src/api/v2/check_documents/prozoro_document_check.py
> +                            and {first_bid['tenderers'][0]['name']} != {second_bid['tenderers'][0]['name']}:
це дуже дивна вимога. навіщо ми створюємо множину буков імені учасника? Якщо я правильно розумію що це учасник. Варто додати коментар, або змінити код.

Також обидва варіанти строк "my little string" і 'my little string' валідні в python, проте в живих проєктах прийнято обрати якийсь один з цих стилів і дотримуватись його. За власним досвідом скажу, що строки "" зазвичай більш зручні, оскільки JSON строго регулює символи визначення строк на відміну від python і більшість копіпасти з JSON в dict. Легше робити з "" строками, ніж з '' строками.

Окремо також наголошу що краще такі поріняння форматувати наступним чином:

```
if (
    doc1["title"] == doc2["title"] and 
    doc1["hash"] == doc2["hash"] and
    {first_bid['tenderers'][0]['name']} != {second_bid['tenderers'][0]['name']}
):
```

Це набагато легше сприймати і загалом є стандартом: 
[python.org/dev/peps/pep-0008/#multiline-if-statements](https://www.python.org/dev/peps/pep-0008/#multiline-if-statements)

2023-02-26 16:07 UTC, sofigern commented on web/urls.py
> +    path('goverla', views.goverla),
Трошки розгублений, що ми двічі використовуємо views.goverla для різних сторінок. Так і заплановано?

2023-03-02 14:21 UTC, ludina001 commented
Зробив в бранчу доповнення. Додано функціонал по траснакціях, новий шаблон для них, трохи по твоїх коментах поправив код (але не весь ще), також трохи переробив шаблон для того функціоналу що ти робив зараз все має +- один вигляд .

2023-03-05 14:06 UTC, sofigern requested changes

2023-03-05 14:06 UTC, sofigern commented on src/api/v2/transactions/transactions_api.py
> +a = {"payers_edrpous": "00035323", "startdate": "2023-02-01", "enddate": "2023-02-27"}
Debug. Можна видалити.

2023-03-05 14:06 UTC, sofigern commented on src/api/v2/transactions/mapper.py
> +    def transform(cls, data):
цю логіку треба буде винести в який-небудь батьківський клас. Вона повторюється для іншого мапера і теперь будь-які зміни до логіки доведеться виконувати в двох файлах одночасно, що не оптимально.

2023-03-05 14:06 UTC, sofigern commented on src/api/parser.py
> +class Parser_Transactions:
Це питання стилів найменувань, але зазвичай так не називають класи. 
Є два класичні стандарти найменувань речей в програмуванні:
- [Camel Case](https://uk.wikipedia.org/wiki/%D0%92%D0%B5%D1%80%D0%B1%D0%BB%D1%8E%D0%B4%D1%8F%D1%87%D0%B8%D0%B9_%D1%80%D0%B5%D0%B3%D1%96%D1%81%D1%82%D1%80)
- [snake_case](https://uk.wikipedia.org/wiki/%D0%97%D0%BC%D1%96%D1%97%D0%BD%D0%B8%D0%B9_%D1%80%D0%B5%D0%B3%D1%96%D1%81%D1%82%D1%80)

Зазвичай в пайтоні класи називають в UpperCamelCase стилі, а все інше (змінні, методи, тощо) в snake_case.
https://peps.python.org/pep-0008/#prescriptive-naming-conventions

2023-03-05 14:06 UTC, sofigern commented on src/api/parser.py
> +    def parse(self, http_response):
спробуй попрацювати з тайпінгом як це в інших місцях роблю я. Це не обовʼязково, але завжди бажано і в будь-якому випадку корисно. 

```
from requests.models import Response
from typing import List
from src.api.v2.transactions.response import TransactionsResponse

def parse(self, http_response: Response) -> List[TransactionsResponse]:
```

Подивись які корисні підказки ти можеш отримати від середовища розробки при вказанні типів. Зверни увагу наскільк легше читати і розуміти поводження класів з такою повною сигнатурою.

Також окреме завдання спробуй виділити щось спільне у двох існуючих парсерах і також перенести це в якийсь базовий клас, щоб не повторювати код.

2023-03-21 08:19 UTC, merged